"""
Inference module for RaksaDana LSTM models.
Exposes functions consumed by the FastAPI backend (main.py).

Expected artifacts per ticker (generated by notebooks 03/04/05):
  models/return_model/return_lstm_{SAFE_TICKER}_seed{42,123,7}.keras
  models/return_model/feature_scaler_{SAFE_TICKER}.pkl
  models/return_model/target_scaler_{SAFE_TICKER}.pkl
  models/return_model/feature_cols_{SAFE_TICKER}.json
  data/processed/{SAFE_TICKER}_featured.csv
  reports/return_model/{SAFE_TICKER}/return_{SAFE_TICKER}_metrics.csv
"""

import json
import pickle
import tempfile
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
MODEL_DIR     = ROOT / "models" / "return_model"
PROCESSED_DIR = ROOT / "data" / "processed"
REPORT_DIR    = ROOT / "reports" / "return_model"

SUPPORTED_TICKERS = ["BBCA.JK", "BBRI.JK", "BMRI.JK"]
DEFAULT_BUY_FEE_RATE = 0.0015
DEFAULT_SELL_FEE_RATE = 0.0025
DEFAULT_LOT_SIZE = 100
BUY_THRESHOLD  =  0.005   # predicted return > +0.5% → BUY
SELL_THRESHOLD = -0.005   # predicted return < -0.5% → SELL

_ARTIFACT_CACHE: dict = {}


# helpers

def _safe(ticker: str) -> str:
    return ticker.replace(".", "_")


def _strip_quantization_config(config):
    if isinstance(config, dict):
        return {
            key: _strip_quantization_config(value)
            for key, value in config.items()
            if key != "quantization_config"
        }
    if isinstance(config, list):
        return [_strip_quantization_config(item) for item in config]
    return config


def _load_keras_model(tf, path: Path):
    try:
        return tf.keras.models.load_model(str(path), compile=False)
    except TypeError as exc:
        if "quantization_config" not in str(exc):
            raise

    temp_path = None
    try:
        with tempfile.NamedTemporaryFile(suffix=".keras", delete=False) as temp_file:
            temp_path = Path(temp_file.name)

        with zipfile.ZipFile(path, "r") as src_zip, zipfile.ZipFile(temp_path, "w") as dst_zip:
            for item in src_zip.infolist():
                content = src_zip.read(item.filename)
                if item.filename == "config.json":
                    config = json.loads(content.decode("utf-8"))
                    content = json.dumps(_strip_quantization_config(config)).encode("utf-8")
                dst_zip.writestr(item, content)

        return tf.keras.models.load_model(str(temp_path), compile=False)
    finally:
        if temp_path and temp_path.exists():
            temp_path.unlink()


def _load_artifacts(ticker: str):
    """Load ensemble, scalers, and feature config for one ticker."""
    if ticker in _ARTIFACT_CACHE:
        return _ARTIFACT_CACHE[ticker]
    import tensorflow as tf

    safe = _safe(ticker)
    config_path = MODEL_DIR / f"feature_cols_{safe}.json"
    if not config_path.exists():
        raise FileNotFoundError(
            f"Feature config not found: {config_path}. Run notebook 03/04/05 first."
        )
    with open(config_path) as f:
        config = json.load(f)
    feature_cols = config["feature_cols"]
    window_size  = config["window_size"]

    with open(MODEL_DIR / f"feature_scaler_{safe}.pkl", "rb") as f:
        feature_scaler = pickle.load(f)
    with open(MODEL_DIR / f"target_scaler_{safe}.pkl", "rb") as f:
        target_scaler = pickle.load(f)

    seeds = [42, 123, 7]
    ensemble = []
    for seed in seeds:
        p = MODEL_DIR / f"return_lstm_{safe}_seed{seed}.keras"
        if p.exists():
            ensemble.append(_load_keras_model(tf, p))

    if not ensemble:
        fallback = MODEL_DIR / f"return_lstm_{safe}_best.keras"
        if fallback.exists():
            ensemble.append(_load_keras_model(tf, fallback))
    if not ensemble:
        raise FileNotFoundError(f"No model found for {ticker}. Run notebook 03/04/05 first.")

    result = (ensemble, feature_scaler, target_scaler, feature_cols, window_size)
    _ARTIFACT_CACHE[ticker] = result
    return result


def _build_window(ticker: str, feature_cols: list, feature_scaler, window_size: int):
    """Build the latest WINDOW_SIZE-step feature window from featured CSV."""
    safe = _safe(ticker)
    path = PROCESSED_DIR / f"{safe}_featured.csv"
    if not path.exists():
        raise FileNotFoundError(f"Featured data not found: {path}. Run notebook 02 first.")

    df = pd.read_csv(path, parse_dates=["Date"]).sort_values("Date").reset_index(drop=True)

    df["Close_Log_Return_1"] = np.log(df["Close"] / df["Close"].shift(1))
    df["Return_3"]           = df["Close"].pct_change(3)
    df["Return_5"]           = df["Close"].pct_change(5)
    df["Return_10"]          = df["Close"].pct_change(10)
    df["Volatility_5"]       = df["Close_Log_Return_1"].rolling(5).std()
    df["Volatility_10"]      = df["Close_Log_Return_1"].rolling(10).std()
    df["Volatility_20"]      = df["Close_Log_Return_1"].rolling(20).std()
    df["Volume_Change"]      = df["Volume"].pct_change()
    df["Volume_Ratio_7"]     = df["Volume"] / df["Volume_MA7"]
    df["MACD_Hist"]          = df["MACD"] - df["MACD_signal"]
    df["BB_width_pct"]       = df["BB_width"] / df["Close"]
    df = df.replace([np.inf, -np.inf], np.nan).dropna(subset=feature_cols)

    if len(df) < window_size:
        raise ValueError(f"Not enough rows ({len(df)}) for window size {window_size}.")

    raw_window = df[feature_cols].iloc[-window_size:].to_numpy(dtype=np.float32)
    last_close = float(df["Close"].iloc[-1])
    last_date  = df["Date"].iloc[-1]
    return raw_window, last_close, last_date, df


def _inv(target_scaler, scaled_pred):
    return float(target_scaler.inverse_transform([[scaled_pred]])[0][0])


def _validate_positive_number(name: str, value: float) -> float:
    try:
        value = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be a number.") from exc
    if not np.isfinite(value) or value <= 0:
        raise ValueError(f"{name} must be greater than 0.")
    return value


def _validate_non_negative_rate(name: str, value: float) -> float:
    try:
        value = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be a number.") from exc
    if not np.isfinite(value) or value < 0:
        raise ValueError(f"{name} must be greater than or equal to 0.")
    if value >= 1:
        raise ValueError(f"{name} must be expressed as a decimal rate below 1.")
    return value


def _validate_whole_number(name: str, value: float) -> int:
    value = _validate_positive_number(name, value)
    if not value.is_integer():
        raise ValueError(f"{name} must be a whole number.")
    return int(value)


def _resolve_share_count(lots=None, shares=None, lot_size: int = DEFAULT_LOT_SIZE) -> int:
    if lots is None and shares is None:
        raise ValueError("Provide either lots or shares.")
    if lots is not None and shares is not None:
        raise ValueError("Provide either lots or shares, not both.")

    lot_size = _validate_whole_number("lot_size", lot_size)
    if lots is not None:
        return _validate_whole_number("lots", lots) * lot_size
    return _validate_whole_number("shares", shares)


# public API

def get_available_tickers() -> list:
    return SUPPORTED_TICKERS


def preload_all() -> None:
    """Warm the artifact cache for all supported tickers."""
    for ticker in SUPPORTED_TICKERS:
        _load_artifacts(ticker)


def predict_next_day(ticker: str) -> dict:
    """
    Predict the next trading day log return, reconstructed close, and signal.

    Returns
    -------
    dict
        ticker, signal_date, base_close, predicted_log_return,
        predicted_close, signal (BUY / HOLD / SELL)
    """
    if ticker not in SUPPORTED_TICKERS:
        raise ValueError(f"Unsupported ticker: {ticker}. Choose from {SUPPORTED_TICKERS}.")

    ensemble, feature_scaler, target_scaler, feature_cols, window_size = _load_artifacts(ticker)
    raw_window, last_close, last_date, _ = _build_window(ticker, feature_cols, feature_scaler, window_size)

    scaled = feature_scaler.transform(raw_window).reshape(1, window_size, len(feature_cols)).astype(np.float32)
    scaled_pred  = float(np.mean([m.predict(scaled, verbose=0).ravel()[0] for m in ensemble]))
    pred_return  = _inv(target_scaler, scaled_pred)
    pred_close   = float(last_close * np.exp(pred_return))

    if pred_return > BUY_THRESHOLD:
        signal = "BUY"
    elif pred_return < SELL_THRESHOLD:
        signal = "SELL"
    else:
        signal = "HOLD"

    next_date = pd.bdate_range(start=last_date + pd.Timedelta(days=1), periods=1)[0]
    return {
        "ticker":                  ticker,
        "signal_date":             str(next_date.date()),
        "base_close":              round(last_close, 2),
        "predicted_log_return":    round(pred_return, 6),
        "predicted_close":         round(pred_close, 2),
        "signal":                  signal,
    }


def forecast_30d(ticker: str, days: int = 30) -> list:
    """
    Recursive multi-step forecast.

    Returns
    -------
    list of dict
        date, predicted_close, predicted_log_return
    """
    if ticker not in SUPPORTED_TICKERS:
        raise ValueError(f"Unsupported ticker: {ticker}.")

    ensemble, feature_scaler, target_scaler, feature_cols, window_size = _load_artifacts(ticker)
    raw_window, last_close, last_date, df = _build_window(ticker, feature_cols, feature_scaler, window_size)

    close_history = list(df["Close"].iloc[-80:].astype(float).values)
    current_close = last_close
    feature_idx   = {name: i for i, name in enumerate(feature_cols)}
    results       = []

    for step_date in pd.bdate_range(start=last_date + pd.Timedelta(days=1), periods=days):
        scaled = feature_scaler.transform(raw_window).reshape(1, window_size, len(feature_cols)).astype(np.float32)
        scaled_pred = float(np.mean([m.predict(scaled, verbose=0).ravel()[0] for m in ensemble]))
        pred_return = _inv(target_scaler, scaled_pred)
        current_close = float(current_close * np.exp(pred_return))

        results.append({
            "date":                  str(step_date.date()),
            "predicted_close":       round(current_close, 2),
            "predicted_log_return":  round(pred_return, 6),
        })

        close_history.append(current_close)
        prices  = pd.Series(close_history)
        returns = pd.Series(np.log(prices / prices.shift(1))).dropna()

        new_row = raw_window[-1].copy()
        updates = {
            "Close_Log_Return_1": pred_return,
            "Daily_Return":       np.exp(pred_return) - 1,
            "Return_3":           prices.pct_change(3).iloc[-1],
            "Return_5":           prices.pct_change(5).iloc[-1],
            "Return_10":          prices.pct_change(10).iloc[-1],
            "Volatility_5":       returns.rolling(5).std().iloc[-1],
            "Volatility_10":      returns.rolling(10).std().iloc[-1],
            "Volatility_20":      returns.rolling(20).std().iloc[-1],
        }
        for name, val in updates.items():
            if name in feature_idx and np.isfinite(val):
                new_row[feature_idx[name]] = val
        raw_window = np.vstack([raw_window[1:], new_row])

    return results


def get_metrics(ticker: str) -> dict:
    """Load saved test metrics for LSTM_Return_Ensemble from CSV."""
    safe = _safe(ticker)
    path = REPORT_DIR / safe / f"return_{safe}_metrics.csv"
    if not path.exists():
        return {}
    df      = pd.read_csv(path)
    test_df = df[(df["Split"] == "Test") & (df["Model"] == "LSTM_Return_Ensemble")]
    if test_df.empty:
        return {}
    row = test_df.iloc[0]
    return {
        "ticker":             ticker,
        "mape":               round(float(row["Price_MAPE"]), 3),
        "r2":                 round(float(row["Price_R2"]), 4),
        "direction_accuracy": round(float(row["Direction_Accuracy"]), 2),
        "return_rmse":        round(float(row["Return_RMSE"]), 6),
    }


def calculate_profit_loss_from_prices(
    ticker: str,
    buy_price: float,
    sell_price: float,
    lots=None,
    shares=None,
    buy_fee_rate: float = DEFAULT_BUY_FEE_RATE,
    sell_fee_rate: float = DEFAULT_SELL_FEE_RATE,
    lot_size: int = DEFAULT_LOT_SIZE,
    price_source: str = "manual",
    exit_date=None,
) -> dict:
    """Calculate gross and net profit/loss from explicit buy and sell prices."""
    buy_price = _validate_positive_number("buy_price", buy_price)
    sell_price = _validate_positive_number("sell_price", sell_price)
    buy_fee_rate = _validate_non_negative_rate("buy_fee_rate", buy_fee_rate)
    sell_fee_rate = _validate_non_negative_rate("sell_fee_rate", sell_fee_rate)
    lot_size = _validate_whole_number("lot_size", lot_size)
    share_count = _resolve_share_count(lots=lots, shares=shares, lot_size=lot_size)

    gross_buy_value = buy_price * share_count
    buy_fee = gross_buy_value * buy_fee_rate
    total_cost = gross_buy_value + buy_fee

    gross_sell_value = sell_price * share_count
    sell_fee = gross_sell_value * sell_fee_rate
    net_proceeds = gross_sell_value - sell_fee

    gross_profit_loss = gross_sell_value - gross_buy_value
    net_profit_loss = net_proceeds - total_cost
    net_return_pct = (net_profit_loss / total_cost) * 100
    price_change_pct = ((sell_price - buy_price) / buy_price) * 100
    breakeven_sell_price = (buy_price * (1 + buy_fee_rate)) / (1 - sell_fee_rate)

    if net_profit_loss > 0:
        status = "PROFIT"
    elif net_profit_loss < 0:
        status = "LOSS"
    else:
        status = "BREAK_EVEN"

    return {
        "ticker": ticker,
        "price_source": price_source,
        "exit_date": exit_date,
        "quantity": {
            "shares": share_count,
            "lots": round(share_count / lot_size, 4),
            "lot_size": lot_size,
        },
        "buy_price": round(buy_price, 2),
        "sell_price": round(sell_price, 2),
        "gross_buy_value": round(gross_buy_value, 2),
        "buy_fee": round(buy_fee, 2),
        "total_cost": round(total_cost, 2),
        "gross_sell_value": round(gross_sell_value, 2),
        "sell_fee": round(sell_fee, 2),
        "net_proceeds": round(net_proceeds, 2),
        "gross_profit_loss": round(gross_profit_loss, 2),
        "net_profit_loss": round(net_profit_loss, 2),
        "net_return_pct": round(net_return_pct, 4),
        "price_change_pct": round(price_change_pct, 4),
        "breakeven_sell_price": round(breakeven_sell_price, 2),
        "status": status,
        "assumptions": {
            "buy_fee_rate": buy_fee_rate,
            "sell_fee_rate": sell_fee_rate,
        },
    }


def calculate_profit_loss(
    ticker: str,
    buy_price: float,
    lots=None,
    shares=None,
    sell_price=None,
    forecast_days=None,
    buy_fee_rate: float = DEFAULT_BUY_FEE_RATE,
    sell_fee_rate: float = DEFAULT_SELL_FEE_RATE,
    lot_size: int = DEFAULT_LOT_SIZE,
) -> dict:
    """
    Calculate estimated profit/loss for an IDX stock position.

    If sell_price is omitted, the calculator uses model output as the exit
    price: predict_next_day for forecast_days None/1, or the last point from
    forecast_30d for forecast_days > 1.
    """
    if ticker not in SUPPORTED_TICKERS:
        raise ValueError(f"Unsupported ticker: {ticker}. Choose from {SUPPORTED_TICKERS}.")

    price_source = "manual"
    exit_date = None
    if sell_price is None:
        if forecast_days is not None:
            forecast_days = _validate_whole_number("forecast_days", forecast_days)

        if forecast_days is None or forecast_days <= 1:
            prediction = predict_next_day(ticker)
            sell_price = prediction["predicted_close"]
            exit_date = prediction["signal_date"]
            price_source = "model_next_day"
        else:
            forecast = forecast_30d(ticker, days=forecast_days)
            prediction = forecast[-1]
            sell_price = prediction["predicted_close"]
            exit_date = prediction["date"]
            price_source = f"model_forecast_{forecast_days}d"

    return calculate_profit_loss_from_prices(
        ticker=ticker,
        buy_price=buy_price,
        sell_price=sell_price,
        lots=lots,
        shares=shares,
        buy_fee_rate=buy_fee_rate,
        sell_fee_rate=sell_fee_rate,
        lot_size=lot_size,
        price_source=price_source,
        exit_date=exit_date,
    )
