"""
Inference module for RaksaDana LSTM models.
Exposes functions consumed by the FastAPI backend (main.py).

Expected artifacts per ticker (generated by notebooks 03/04/05):
  models/return_model/return_lstm_{SAFE_TICKER}_seed{42,123,7}.keras
  models/return_model/feature_scaler_{SAFE_TICKER}.pkl
  models/return_model/target_scaler_{SAFE_TICKER}.pkl
  models/return_model/feature_cols_{SAFE_TICKER}.json
  data/processed/{SAFE_TICKER}_featured.csv
  reports/return_model/{SAFE_TICKER}/return_{SAFE_TICKER}_metrics.csv
"""

import json
import pickle
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
MODEL_DIR     = ROOT / "models" / "return_model"
PROCESSED_DIR = ROOT / "data" / "processed"
REPORT_DIR    = ROOT / "reports" / "return_model"

SUPPORTED_TICKERS = ["BBCA.JK", "BBRI.JK", "BMRI.JK"]
BUY_THRESHOLD  =  0.005   # predicted return > +0.5% → BUY
SELL_THRESHOLD = -0.005   # predicted return < -0.5% → SELL


# ── helpers ──────────────────────────────────────────────────────────────────

def _safe(ticker: str) -> str:
    return ticker.replace(".", "_")


def _load_artifacts(ticker: str):
    """Load ensemble, scalers, and feature config for one ticker."""
    import tensorflow as tf

    safe = _safe(ticker)
    config_path = MODEL_DIR / f"feature_cols_{safe}.json"
    if not config_path.exists():
        raise FileNotFoundError(
            f"Feature config not found: {config_path}. Run notebook 03/04/05 first."
        )
    with open(config_path) as f:
        config = json.load(f)
    feature_cols = config["feature_cols"]
    window_size  = config["window_size"]

    with open(MODEL_DIR / f"feature_scaler_{safe}.pkl", "rb") as f:
        feature_scaler = pickle.load(f)
    with open(MODEL_DIR / f"target_scaler_{safe}.pkl", "rb") as f:
        target_scaler = pickle.load(f)

    seeds = [42, 123, 7]
    ensemble = []
    for seed in seeds:
        p = MODEL_DIR / f"return_lstm_{safe}_seed{seed}.keras"
        if p.exists():
            ensemble.append(tf.keras.models.load_model(str(p)))

    if not ensemble:
        fallback = MODEL_DIR / f"return_lstm_{safe}_best.keras"
        if fallback.exists():
            ensemble.append(tf.keras.models.load_model(str(fallback)))
    if not ensemble:
        raise FileNotFoundError(f"No model found for {ticker}. Run notebook 03/04/05 first.")

    return ensemble, feature_scaler, target_scaler, feature_cols, window_size


def _build_window(ticker: str, feature_cols: list, feature_scaler, window_size: int):
    """Build the latest WINDOW_SIZE-step feature window from featured CSV."""
    safe = _safe(ticker)
    path = PROCESSED_DIR / f"{safe}_featured.csv"
    if not path.exists():
        raise FileNotFoundError(f"Featured data not found: {path}. Run notebook 02 first.")

    df = pd.read_csv(path, parse_dates=["Date"]).sort_values("Date").reset_index(drop=True)

    df["Close_Log_Return_1"] = np.log(df["Close"] / df["Close"].shift(1))
    df["Return_3"]           = df["Close"].pct_change(3)
    df["Return_5"]           = df["Close"].pct_change(5)
    df["Return_10"]          = df["Close"].pct_change(10)
    df["Volatility_5"]       = df["Close_Log_Return_1"].rolling(5).std()
    df["Volatility_10"]      = df["Close_Log_Return_1"].rolling(10).std()
    df["Volatility_20"]      = df["Close_Log_Return_1"].rolling(20).std()
    df["Volume_Change"]      = df["Volume"].pct_change()
    df["Volume_Ratio_7"]     = df["Volume"] / df["Volume_MA7"]
    df["MACD_Hist"]          = df["MACD"] - df["MACD_signal"]
    df["BB_width_pct"]       = df["BB_width"] / df["Close"]
    df = df.replace([np.inf, -np.inf], np.nan).dropna(subset=feature_cols)

    if len(df) < window_size:
        raise ValueError(f"Not enough rows ({len(df)}) for window size {window_size}.")

    raw_window = df[feature_cols].iloc[-window_size:].to_numpy(dtype=np.float32)
    last_close = float(df["Close"].iloc[-1])
    last_date  = df["Date"].iloc[-1]
    return raw_window, last_close, last_date, df


def _inv(target_scaler, scaled_pred):
    return float(target_scaler.inverse_transform([[scaled_pred]])[0][0])


# ── public API ────────────────────────────────────────────────────────────────

def get_available_tickers() -> list:
    return SUPPORTED_TICKERS


def predict_next_day(ticker: str) -> dict:
    """
    Predict the next trading day log return, reconstructed close, and signal.

    Returns
    -------
    dict
        ticker, signal_date, base_close, predicted_log_return,
        predicted_close, signal (BUY / HOLD / SELL)
    """
    if ticker not in SUPPORTED_TICKERS:
        raise ValueError(f"Unsupported ticker: {ticker}. Choose from {SUPPORTED_TICKERS}.")

    ensemble, feature_scaler, target_scaler, feature_cols, window_size = _load_artifacts(ticker)
    raw_window, last_close, last_date, _ = _build_window(ticker, feature_cols, feature_scaler, window_size)

    scaled = feature_scaler.transform(raw_window).reshape(1, window_size, len(feature_cols)).astype(np.float32)
    scaled_pred  = float(np.mean([m.predict(scaled, verbose=0).ravel()[0] for m in ensemble]))
    pred_return  = _inv(target_scaler, scaled_pred)
    pred_close   = float(last_close * np.exp(pred_return))

    if pred_return > BUY_THRESHOLD:
        signal = "BUY"
    elif pred_return < SELL_THRESHOLD:
        signal = "SELL"
    else:
        signal = "HOLD"

    next_date = pd.bdate_range(start=last_date + pd.Timedelta(days=1), periods=1)[0]
    return {
        "ticker":                  ticker,
        "signal_date":             str(next_date.date()),
        "base_close":              round(last_close, 2),
        "predicted_log_return":    round(pred_return, 6),
        "predicted_close":         round(pred_close, 2),
        "signal":                  signal,
    }


def forecast_30d(ticker: str, days: int = 30) -> list:
    """
    Recursive multi-step forecast.

    Returns
    -------
    list of dict
        date, predicted_close, predicted_log_return
    """
    if ticker not in SUPPORTED_TICKERS:
        raise ValueError(f"Unsupported ticker: {ticker}.")

    ensemble, feature_scaler, target_scaler, feature_cols, window_size = _load_artifacts(ticker)
    raw_window, last_close, last_date, df = _build_window(ticker, feature_cols, feature_scaler, window_size)

    close_history = list(df["Close"].iloc[-80:].astype(float).values)
    current_close = last_close
    feature_idx   = {name: i for i, name in enumerate(feature_cols)}
    results       = []

    for step_date in pd.bdate_range(start=last_date + pd.Timedelta(days=1), periods=days):
        scaled = feature_scaler.transform(raw_window).reshape(1, window_size, len(feature_cols)).astype(np.float32)
        scaled_pred = float(np.mean([m.predict(scaled, verbose=0).ravel()[0] for m in ensemble]))
        pred_return = _inv(target_scaler, scaled_pred)
        current_close = float(current_close * np.exp(pred_return))

        results.append({
            "date":                  str(step_date.date()),
            "predicted_close":       round(current_close, 2),
            "predicted_log_return":  round(pred_return, 6),
        })

        close_history.append(current_close)
        prices  = pd.Series(close_history)
        returns = np.log(prices / prices.shift(1)).dropna()

        new_row = raw_window[-1].copy()
        updates = {
            "Close_Log_Return_1": pred_return,
            "Daily_Return":       np.exp(pred_return) - 1,
            "Return_3":           prices.pct_change(3).iloc[-1],
            "Return_5":           prices.pct_change(5).iloc[-1],
            "Return_10":          prices.pct_change(10).iloc[-1],
            "Volatility_5":       returns.rolling(5).std().iloc[-1],
            "Volatility_10":      returns.rolling(10).std().iloc[-1],
            "Volatility_20":      returns.rolling(20).std().iloc[-1],
        }
        for name, val in updates.items():
            if name in feature_idx and np.isfinite(val):
                new_row[feature_idx[name]] = val
        raw_window = np.vstack([raw_window[1:], new_row])

    return results


def get_metrics(ticker: str) -> dict:
    """Load saved test metrics for LSTM_Return_Ensemble from CSV."""
    safe = _safe(ticker)
    path = REPORT_DIR / safe / f"return_{safe}_metrics.csv"
    if not path.exists():
        return {}
    df      = pd.read_csv(path)
    test_df = df[(df["Split"] == "Test") & (df["Model"] == "LSTM_Return_Ensemble")]
    if test_df.empty:
        return {}
    row = test_df.iloc[0]
    return {
        "ticker":             ticker,
        "mape":               round(float(row["Price_MAPE"]), 3),
        "r2":                 round(float(row["Price_R2"]), 4),
        "direction_accuracy": round(float(row["Direction_Accuracy"]), 2),
        "return_rmse":        round(float(row["Return_RMSE"]), 6),
    }
